# Generated by Django 6.1.1 on 2026-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_payment_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
